# -*- coding: utf-8 -*-
"""weather_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zjg9tvTLq6QuSa1zMD5uFYriLoUNQMnO
"""

!pip install pydrive openpyxl

import pandas as pd
import numpy as np
from google.colab import drive
import openpyxl
import os


drive.mount('/content/drive')

os.chdir('/content/drive/MyDrive/SIL/Weather_data/weather_data')

!ls # to get the name of all files of your folder

# List of file names
file_names = [
    'W. 2015_2 Kenya (SFS_3 locs).xlsx',	'W. 2020_1 Mali.xlsx',
    'W. 2016_1 Kenya (SFS_2 locs).xlsx',	'W. 2020_1 Myanmar.xlsx',
    'W. 2016_2 Kenya (SFS_2 locs).xlsx',	'W.2020_1 Togo (GLK_1 loc).xlsx',
    'W. 2017_1 Kenya (SFS_4 locs).xlsx',	'W. 2020_2 Kenya.xlsx',
    'W. 2017_1 Mali (SFS_2 locs).xlsx',	'W. 2020_2 Malawi.xlsx',
    'W. 2017_2 Kenya (SFS_1 loc).xlsx',	'W. 2020_2 Mozambique (IIT_2 locs).xlsx',
    'W. 2017_2 Malawi (7 locs).xlsx',	'W. 2020_2 Rwanda (OAF_ 2 locs).xlsx',
    'W. 2018_1 Malawi.xlsx',			'W. 2020_2 Uganda (AGI_1 loc).xlsx',
    'W. 2018_2 Cameroon.xlsx',	'W. 2020_2 Zambia.xlsx',
    'W. 2018_2 Malawi.xlsx',			'W. 2020_2 Zimbabwe (8 locs).xlsx',
    'W. 2018_2 Mozambique.xlsx',		'W. 2021_1 Ethiopia (JEI_3 locs).xlsx',
    'W. 2018_2 Rwanda.xlsx',			'W. 2021_1 Kenya (KAL_1 loc)_01.05.21_11.27.21.xlsx',
    'W. 2018_2 Uganda.xlsx',			'W. 2021_1 Kenya (KAL_1 loc)_until Jan 22.xlsx',
    'W. 2018_2 Zimbabwe (10 locs).xlsx',	'W. 2021_1 Malawi.xlsx',
    'W. 2019_1 Benin.xlsx',			'W. 2021_1 Rwanda (OAF_2 locs).xlsx',
    'W. 2019_1 Ethiopia.xlsx',		'W. 2021_1 Senegal (UAS_1 loc).xlsx',
    'W. 2019_1 Ghana.xlsx',			'W. 2021_1 South Sudan (FST_3 locs).xlsx',
    'W. 2019_1 Kenya (4 locs).xlsx',		'W. 2021_2 Bangladesh (LAL_3 locs).xlsx',
    'W. 2019_1 Malawi.xlsx',			'W.2021_2 Kenya (SFS_3 locs).xlsx',
    'W. 2019_1 Mali.xlsx',			'W. 2021_2 Malawi (PYX_2 locs).xlsx',
    'W. 2019_1 Nigeria (IIT 2 locs).xlsx',	'W. 2021_2 Mozambique (IIT_3 locs).xlsx',
    'W. 2019_1 Uganda.xlsx',			'W. 2021_2 Namibia (MAW_6 locs).xlsx',
    'W. 2019_1 Zimbabwe (CBI_2 locs).xlsx',	'W. 2021_2 Somalia (CSK_1 loc).xlsx',
    'W. 2019_2 Cameroon.xlsx',		'W. 2021_2 Zambia (8 locs).xlsx',
    'W. 2019_2 Malawi.xlsx'	,		'W. 2021_2 Zimbabwe (CBI_4 locs).xlsx',
    'W. 2019_2 Mozambique.xlsx',	'W. 2021_2 Zimbabwe (KKR_1 loc).xlsx',
    'W. 2019_2 Uganda (AGI_1 loc).xlsx',	'W. 2021_2 Zimbabwe (SCL_3 locs).xlsx',
    'W. 2019_2 Zambia.xlsx',			'W. 2022_1 Malawi (PYX_2 locs).xlsx',
    'W. 2019_2 Zimbabwe (9 locs).xlsx',	'W. 2022_1 Rwanda (OAF_2 locs).xlsx',
    'W. 2020_1 Benin.xlsx',			'W. 2022_1 South Sudan (FST_1 loc).xlsx',
    'W. 2020_1 Ethiopia.xlsx'	,	'W. 2022_1 Tajikistan (GLP_2 locs).xlsx',
    'W. 2020_1 Ghana.xlsx',			'W. 2022_2 Malawi (AGC_1 loc).xlsx',
    'W. 2020_1 Kenya.xlsx',			'W. 2022_2 Malawi (LLM_1 loc).xlsx',
    'W. 2020_1 Malawi.xlsx',			'W. 2022_2 Rwanda (OAF_2 locs).xlsx',
]

# Function to extract tabs starting with "Weather of"
def extract_weather_tabs(file_name):
    try:
        workbook = openpyxl.load_workbook(file_name, data_only=True)
        weather_tabs = [sheet for sheet in workbook.sheetnames if sheet.startswith("Weather at")]

        tab_contents = {}

        for sheet_name in weather_tabs:
            sheet = workbook[sheet_name]
            data = []
            for row in sheet.iter_rows(values_only=True):
                data.append(row)

            tab_contents[sheet_name] = data

        return tab_contents
    except FileNotFoundError:
        print(f"File '{file_name}' not found.")
    except Exception as e:
        print(f"An error occurred while processing '{file_name}': {e}")
        return None

# Read and process the desired tabs in each file
file_data = {}

for file_name in file_names:
    tab_contents = extract_weather_tabs(file_name)
    if tab_contents is not None:
        file_data[file_name] = tab_contents

# Now, file_data is a dictionary with file names as keys and the content of the "Weather of" tabs as values.

file_data

# Create an empty list to store data in a flat structure
flat_data = []

for file_name, tab_data_dict in file_data.items():
    for tab_name, tab_data in tab_data_dict.items():
        for row in tab_data:
            flat_data.append([file_name, tab_name] + list(row))

# Convert the flat data list into a Pandas DataFrame
new_df = pd.DataFrame(flat_data, columns=['File', 'Tab', 'Day', 'Max. temp.', 'Mean temp.', 'Min. temp.', 'Precipitations'])

# Display the resulting DataFrame
new_df

# Clean the 'Tab' column by removing "Weather at " prefix
new_df['Tab'] = new_df['Tab'].str.replace('Weather at ', '')

new_df

new_df = new_df.drop('File', axis=1)

new_df

# Define the path for the CSV file in your Google Drive
csv_file_path = '/content/drive/My Drive/SIL/weather_data.csv'

# Save the DataFrame to CSV
new_df.to_csv(csv_file_path, index=False)
